CREATE TABLE task_assignees(
 id serial PRIMARY KEY,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE,
 created_at TIMESTAMP NOT NULL
);
